const path = require('path');
const fs = require('fs');

function slugify(name){
  return name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
}

// Función para cargar proyectos desde jurassic.projects.json
function loadProjects() {
  try {
    const configFile = path.join(__dirname, 'jurassic.projects.json');
    const raw = JSON.parse(fs.readFileSync(configFile, 'utf8'));
    const projects = raw.projects || [];
    
    return projects
      .map(relPath => {
        const absPath = path.resolve(__dirname, relPath);
        const docsPath = path.join(absPath, '.docusaurus', 'docs');
        const markdownPath = path.join(absPath, '.docusaurus', 'markdown');
        
        let detectedFolder = null;
        if (fs.existsSync(docsPath)) {
          detectedFolder = docsPath;
        } else if (fs.existsSync(markdownPath)) {
          detectedFolder = markdownPath;
        }
        
        return detectedFolder ? {
          abs: absPath,
          detected: { folder: detectedFolder, type: 'docs' }
        } : null;
      })
      .filter(Boolean);
  } catch (error) {
    console.warn('[JurassicDocs] Error cargando proyectos:', error.message);
    return [];
  }
}

const dynamicProjects = loadProjects();
console.log('[JurassicDocs] Proyectos detectados:', dynamicProjects.map(p => p.abs));

const docsPlugins = dynamicProjects.map(p => {
  const name = path.basename(p.abs);
  const slug = slugify(name);
  const pluginId = `jurassic-${slug}`;
  return [
    '@docusaurus/plugin-content-docs',
    {
      id: pluginId,
      path: p.detected.folder,
      routeBasePath: slug,
      include: ['**/*.md','**/*.mdx'],
      sidebarPath: require.resolve('./sidebars.js'),
      editCurrentVersion: false,
    }
  ];
});

module.exports = {
  title: 'Jurassic Docs',
  tagline: '🦕 Documentación unificada multi-proyecto',
  url: 'http://localhost',
  baseUrl: '/',
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'jurassic',
  projectName: 'jurassic-docs',
  trailingSlash: false,
  
  i18n: { 
    defaultLocale: 'es', 
    locales: ['es'],
    localeConfigs: {
      es: {
        label: 'Español',
        direction: 'ltr',
        htmlLang: 'es-ES',
      },
    },
  },
  presets: [
    [
      'classic',
      {
        docs: {
          id: 'jurassic-internal',
          path: 'docs',
          routeBasePath: 'jurassic',
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: 'https://github.com/tu-usuario/jurassic-docs/edit/main/',
        },
        blog: false,
        pages: {},
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        }
      }
    ]
  ],
  plugins: [
    ...docsPlugins
  ],
  themeConfig: {
    navbar: {
      title: '🦕 Jurassic Docs',
      logo: {
        alt: 'Jurassic Docs Logo',
        src: 'img/logo.svg',
        width: 32,
        height: 32,
      },
      items: [
        { to: '/jurassic/intro', label: '🏠 Inicio', type: 'docSidebar', sidebarId: 'autogenerated', docsPluginId: 'jurassic-internal' },
        ...dynamicProjects.map(p=>{
          const name = path.basename(p.abs);
          const slug = slugify(name);
          return {
            label: `📦 ${name}`,
            type: 'docSidebar',
            sidebarId: 'autogenerated',
            docsPluginId: `jurassic-${slug}`
          };
        }),
        {
          href: 'https://github.com/tu-usuario/jurassic-docs',
          label: 'GitHub',
          position: 'right',
        },
      ],
      hideOnScroll: true,
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: '📚 Documentación',
          items: [
            {
              label: '🚀 Guía de uso',
              to: '/jurassic/guia-uso',
            },
            {
              label: '⚙️ Configuración',
              to: '/jurassic/configuracion',
            },
            {
              label: '🏗️ Arquitectura',
              to: '/jurassic/arquitectura',
            },
          ],
        },
        {
          title: '🔧 Referencia',
          items: [
            {
              label: '📖 API Reference',
              to: '/jurassic/api-reference',
            },
            {
              label: '🐛 Troubleshooting',
              to: '/jurassic/troubleshooting',
            },
          ],
        },
        {
          title: '🌐 Comunidad',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/tu-usuario/jurassic-docs',
            },
            {
              label: 'Docusaurus',
              href: 'https://docusaurus.io',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Jurassic Docs. Construido con 🦕 y ❤️.`,
    },
    prism: {
      theme: require('prism-react-renderer/themes/github'),
      darkTheme: require('prism-react-renderer/themes/dracula'),
      additionalLanguages: ['bash', 'json', 'yaml'],
    },
    colorMode: {
      defaultMode: 'light',
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
    docs: {
      sidebar: {
        hideable: true,
        autoCollapseCategories: true,
      },
    },
  }
};
